mysql:
  image: hub.caishuo.com/mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: '1234'
redis:
  image: hub.caishuo.com/redis
html:
  image: hub.caishuo.com/html
  links:
    - web
  ports:
    - "80:80"
web:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -e docker_dev
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  cpu_shares: 5
  links:
    - mysql
    - redis
  environment:
    RACK_ENV: 'docker_dev'
