defaults: &defaults
  host: 192.168.1.10
  port: 6379
development:
  <<: *defaults
  # host: localhost
  # host: 192.168.1.11
test:
  <<: *defaults
  host: localhost
staging:
  <<: *defaults
production:
  <<: *defaults
